### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by EmisThePro1stLT** [Embe-Codez/embe-codez#2]
Hey! I was wondering if you could help me with one of your already made repos and provide more info. Maybe you got discord? If so heres mine: 3m1c

**Comment by Embe-Codez** [comment]
Which repo?

**Comment by EmisThePro1stLT** [comment]
> Which repo?

The "bolt4free"

**Comment by Embe-Codez** [comment]
Wish I could, but I believe that vulnerability has been patched by the vendor. That code was just rewritten by me, and the original person that discovered it mentioned it had been patched.

**Comment by EmisThePro1stLT** [comment]
Interesting, do you have any idea on what got changed/ how it got patched?
Because when I was checking it out I saw it was Germany servers, here i
came to conclusion it sort of works still, im not sure though.
